image: registry.gitlab.com/pages/hugo:latest

before_script:
  - hugo version
  - git --version

stages:
  - deploy


# Mirror Gitlab repository to Github
mirroring:
  stage: deploy
  only:
    - master
  before_script:
    - git config user.email "ardianta_pargo@yahoo.co.id"
    - git config --global user.name "ardianta"
  script:
    - git remote add github https://ardianta:$GITHUB_ACCESS_TOKEN@github.com/ardianta/blog.git
    - git push github --all    

# Deploy to github pages  
github_pages:
  stage: deploy
  only:
    - master
  script:
    - git clone --depth 1 https://ardianta:$GITHUB_ACCESS_TOKEN@github.com/ardianta/ardianta.github.io.git public
    - mv public/.git /tmp/.git # backup .git
    - rm -rf public/* # clean old build
    - hugo --minify # build site
    - mv /tmp/.git public/.git # restore .git
    - cd public
    - git config user.email "ardianta_pargo@yahoo.co.id"
    - git config --global user.name "ardianta"
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
  after_script:
    - cd ..
    - rm -rf public