image: registry.gitlab.com/pages/hugo:latest

before_script:
  - hugo version
  - git --version

stages:
  - deploy

# Deploy to github pages  
github_pages:
  stage: deploy
  only:
    - master
  script:
    - git clone --depth 1 https://ardianta:$GITHUB_ACCESS_TOKEN@github.com/ardianta/ardianta.github.io.git public
    - mv public/.git /tmp/.git # backup .git
    - rm -rf public/* # clean old build
    - hugo --minify # build site
    - mv /tmp/.git public/.git # restore .git
    - cd public
    - git config user.email $GIT_EMAIL
    - git config --global $GIT_USER
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
    - exit 0